

# This file was *autogenerated* from the file ./solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_100001 = Integer(100001)#!/usr/bin/env sage
bound = _sage_const_10  ** _sage_const_12 
denom_sum = _sage_const_0 
for n in range(_sage_const_2 , _sage_const_100001 ):
    if int(sqrt(n)) ** _sage_const_2  == n:
        continue
    approx = sqrt(n).n(_sage_const_200 ).nearby_rational(max_denominator=bound)
    # print("{}\t{}".format(n, approx))
    denom_sum += approx.denominator()
print(denom_sum)

